version: 2
jobs:
  build:
    docker:
      - image: debian:sid
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command:  apt-get update &&  apt-get install -y build-essential make cmake libcurl4-openssl-dev libjson-c-dev valgrind lcov gcovr
      - run:
          name: Tests + Coverage
          command: mkdir build && cd build && cmake .. -DWITH_PROF=ON && make coverage
      - run:
          name: Valgrind
          command: cd build/ && valgrind --error-exitcode=42 --leak-check=full ./sentry_test
