version: 2
jobs:
  build:
    docker:
      - image: debian:sid
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command:  apt-get update &&  apt-get install -y build-essential make cmake libcurl4-openssl-dev libjson-c-dev
      - run:
          name: Build
          command: mkdir build && cd build && cmake .. && make
