version: 2
jobs:
  build:
    docker:
      - image: debian:sid
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command:  apt-get update &&  apt-get install -y build-essential make cmake libcurl4-openssl-dev libjson-c-dev valgrind
      - run:
          name: Build
          command: mkdir build && cd build && cmake .. && make check
      - run:
          name: Valgrind
          command: valgrind --error-exitcode=42 --leak-check=full ./sentry_test
