version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Build
          command: mkdir build
          command: cd build
          command: cmake ..
          command: make
